export * from './Main'
export * from './Resources'
export * from './Portfolio'
export * from './Education'
export * from './Experience'
export * from './Projects'
export * from './Brands'
export * from './Footer'